/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MergerJsFilePnl.java
 *
 * Created on 2013-3-14, 11:04:07
 */
package jsanalysis.ui;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import jsanalysis.common.FileWriteUtils;
import jsanalysis.common.Utils;
import jsanalysis.test.ImageUtils;

/**
 *
 * @author zhangwei <laketea@163.com>
 */
public class ExportPnl extends javax.swing.JPanel {

    private String path = "";
    private String fileType = "";
    private JComponent jcp;
    private boolean isImgExport = false;
    private String result = "";

    /** Creates new form MergerJsFilePnl */
    public ExportPnl(String fileType, JComponent jcp, String result) {
        initComponents();
        this.fileType = fileType;
        this.jcp = jcp;
        this.result = result;
        if ("img".equals(fileType)) {
            isImgExport = true;
        }
        this.jtfFileName.setText(isImgExport ? "result.jpg" : "result.txt");
    }

    private void exportTextAction() {
        if (!Utils.notBank(jtfPath.getText()) || !Utils.notBank(jtfFileName.getText())) {
            Utils.showMesaage(this, "导出文件路径或文件名不能为空!");
            return;
        }
        String filePathName = jtfPath.getText() + File.separator + jtfFileName.getText();
//        if (!Utils.notBank(result)) {
//            Utils.showMesaage(this, "您要导出的js内容为空，请确认选择的目录下是否存在js文件!");
//            return;
//        }
        try {
            FileWriteUtils.bestWriteFile(result, jtfPath.getText() + File.separator + jtfFileName.getText());
        } catch (Exception ex) {
            ex.printStackTrace();
            Utils.showMesaage(this, "文件保存失败！");
            exit();
            return;
        }
        Utils.showMesaage(this, "文件保存成功！导出文件为:" + filePathName);
        exit();
        return;
    }

    private void exportImgAction() {
        if (!Utils.notBank(jtfPath.getText()) || !Utils.notBank(jtfFileName.getText())) {
            Utils.showMesaage(this, "导出文件路径或文件名不能为空!");
            return;
        }
        String filePathName = jtfPath.getText() + File.separator + jtfFileName.getText();
        try {
            (new ImageUtils()).exportImg(jcp, filePathName);
        } catch (IOException ex) {
            ex.printStackTrace();
            Utils.showMesaage(this, "文件保存失败！");
            exit();
        }
        Utils.showMesaage(this, "文件保存成功！导出文件为:" + filePathName);
        exit();
        return;
    }

    private void exit() {
        SwingUtilities.getWindowAncestor(this).dispose();
    }

    private void selectExportPath() {
        path = selectDirectoryDialog();
//        if (!Utils.notBank(path) || !(new File(path).exists())) {
//            Utils.showMesaage(this, "无效的目录，请重新选择!");
//            return;
//        }
        jtfPath.setText(path);
    }

    //弹出文件目录选择框
    private String selectDirectoryDialog() {
        String path = "";
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        int retval = chooser.showOpenDialog(this);//显示“打开文件”对话框
        if (retval == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            path = file.getAbsolutePath();
        }
        return path;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfPath = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfFileName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("设置导出目录"));

        jLabel1.setText("导出目录:");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("导出文件名:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jtfFileName)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jtfPath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfFileName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jButton1)
                .add(18, 18, 18)
                .add(jButton2)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1))
                .add(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        selectExportPath();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (isImgExport) {
            exportImgAction();
        } else {
            exportTextAction();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfFileName;
    private javax.swing.JTextField jtfPath;
    // End of variables declaration//GEN-END:variables
}
